# NumPy Basics: Arrays and 

In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)
plt.show()

In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 8 ms
Wall time: 384 ms


## The NumPy ndarray: A Multidimensional Array Object

In [9]:
import numpy as np
# Generate some random data
data = np.random.randn(10, 5)
data

array([[-2.0016, -0.3718,  1.669 , -0.4386, -0.5397],
       [ 0.477 ,  3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438, -0.7135],
       [-0.8312, -2.3702, -1.8608, -0.8608,  0.5601],
       [-1.2659,  0.1198, -1.0635,  0.3329, -2.3594],
       [-0.1995, -1.542 , -0.9707, -1.307 ,  0.2863],
       [ 0.378 , -0.7539,  0.3313,  1.3497,  0.0699],
       [ 0.2467, -0.0119,  1.0048,  1.3272, -0.9193],
       [-1.5491,  0.0222,  0.7584, -0.6605,  0.8626],
       [-0.01  ,  0.05  ,  0.6702,  0.853 , -0.9559]])

In [10]:
data * 10

array([[-20.0164,  -3.7184,  16.6903,  -4.3857,  -5.3974],
       [  4.7699,  32.4894, -10.2123,  -5.7709,   1.2412],
       [  3.0261,   5.2377,   0.0094,  13.4381,  -7.1354],
       [ -8.3115, -23.7023, -18.6076,  -8.6076,   5.6015],
       [-12.6593,   1.1983, -10.6351,   3.3288, -23.5942],
       [ -1.9954, -15.42  ,  -9.7074, -13.0703,   2.8635],
       [  3.7798,  -7.5389,   3.3129,  13.4974,   0.6988],
       [  2.4667,  -0.1186,  10.0481,  13.2719,  -9.1926],
       [-15.4911,   0.2218,   7.5836,  -6.6052,   8.6258],
       [ -0.1003,   0.5001,   6.7022,   8.5297,  -9.5587]])

In [11]:
data + data

array([[-4.0033, -0.7437,  3.3381, -0.8771, -1.0795],
       [ 0.954 ,  6.4979, -2.0425, -1.1542,  0.2482],
       [ 0.6052,  1.0475,  0.0019,  2.6876, -1.4271],
       [-1.6623, -4.7405, -3.7215, -1.7215,  1.1203],
       [-2.5319,  0.2397, -2.127 ,  0.6658, -4.7188],
       [-0.3991, -3.084 , -1.9415, -2.6141,  0.5727],
       [ 0.756 , -1.5078,  0.6626,  2.6995,  0.1398],
       [ 0.4933, -0.0237,  2.0096,  2.6544, -1.8385],
       [-3.0982,  0.0444,  1.5167, -1.321 ,  1.7252],
       [-0.0201,  0.1   ,  1.3404,  1.7059, -1.9117]])

In [12]:
data.shape

(10, 5)

In [13]:
data.dtype


dtype('float64')

In [1]:
data2 = np.array([ 3, 4, 'dwadwa'])
data2.dtype

NameError: name 'np' is not defined

### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim
# arr2.shape

2

In [12]:
arr1.dtype
arr2.dtype

dtype('int64')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2, 3, 2))

array([[[4.67858595e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float32)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float32')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [21]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [22]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [23]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [24]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [30]:
arr = np.arange(10)
arr
# arr[5]
arr[5:8]

array([5, 6, 7])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [38]:
arr2d[0][2]
arr2d[0, 2]

3

In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
old_values = arr3d[0].copy()
arr3d[0] = 42
old_values
# arr3d[0] = old_values
# arr3d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
old_values

In [42]:
arr3d[1, 0]

array([7, 8, 9])

In [ ]:
x = arr3d[1]
x
x[0]

#### Indexing with slices

In [43]:
arr
arr[1:6]
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [44]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr2d[1, :2]

array([4, 5])

In [49]:
arr2d[:2, 2]

array([3, 6])

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [52]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 0.3536,  0.7021, -0.2746, -0.1391],
       [ 0.1077, -0.6065, -0.4171, -0.017 ],
       [-1.2241, -1.8008,  1.6347,  0.989 ],
       [ 0.4579,  0.5552,  1.3067, -0.4406],
       [-0.3014,  0.4988, -0.824 ,  1.3206],
       [ 0.508 , -0.6534,  0.187 , -0.3917],
       [-0.2723, -0.0171,  0.6803,  0.6355]])

In [55]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [56]:
data[names == 'Bob']

array([[-1.34482302,  2.10905823, -0.3739341 ,  1.25651193],
       [-1.039615  ,  0.02784309, -2.79742695,  0.05427971]])

In [57]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

array([1.25651193, 0.05427971])

In [58]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 1.8776704 , -0.66246599, -0.85898022,  1.62929364],
       [-0.42120095, -0.1860675 ,  0.9238686 ,  0.32145545],
       [ 0.48730398, -0.8870136 , -2.30280154, -0.52196371],
       [ 0.39570236, -1.34385357,  0.04396295, -0.71546689],
       [-1.50580081, -0.47829695, -0.71559265,  0.36476521]])

In [ ]:
data

In [ ]:
cond = names == 'Bob'
cond
~cond
data[~cond]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### Fancy Indexing

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

### Transposing Arrays and Swapping Axes

In [59]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [60]:
arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

array([[ 5.90352384, -1.36098886,  0.98741438],
       [-1.36098886,  2.98233718, -0.02647845],
       [ 0.98741438, -0.02647845,  4.82773937]])

In [61]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [62]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [63]:
arr = np.arange(10)
arr
np.sqrt(arr)
# np.exp(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [64]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

array([ 0.55113871,  1.38119303,  1.03163143, -0.12765064,  0.94600382,
        1.27512468, -0.21751033,  0.10826411])

In [65]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

array([ 5.,  3., -7.,  0., -1.,  3.,  5.])

In [ ]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

## Array-Oriented Programming with Arrays

In [66]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [67]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

### Expressing Conditional Logic as Array Operations

In [68]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [69]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [70]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [72]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[-2, -2,  2,  2],
       [-2, -2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2, -2]])

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [73]:
arr = np.random.randn(5, 4)
arr
arr.mean()
# np.mean(arr)
arr.sum()

-1.4771972793065007

In [74]:
arr.mean(axis=1)
arr.sum(axis=0)

array([-3.20588435, -1.37254051, -0.35840697,  3.45963455])

In [75]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [76]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [77]:
arr = np.random.randn(6)
arr
arr.sort()
arr

array([-1.63442898, -0.93084099, -0.83289416,  0.03102615,  0.25129851,
        0.45608338])

In [78]:
arr = np.random.randn(5, 3)
arr
arr.sort(1)
arr

array([[-1.5613997 ,  0.16806712,  1.62696516],
       [-0.51115088,  0.11409234,  1.01280278],
       [-0.38396886,  0.47786055,  0.93381457],
       [-1.16880468, -0.36940129, -0.01464214],
       [-2.39170312, -1.14645601,  0.62203374]])

In [79]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.621530541080189

### Unique and Other Set Logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
# ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
# np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File Input and Output with Arrays

In [80]:
arr = np.arange(10)
np.save('some_array', arr)

In [81]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.savez('array_archive.npz', a=arr, b=arr)

In [83]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Pseudorandom Number Generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)